version: '3.8'

services:
  db:
    image: mariadb:latest
    secrets_file:
      - secrets.env
    volumes:
      - mariadb_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8009:8000"
    depends_on:
      - db

volumes:
  mariadb_data:
